network_file: "net/onset_and_pitch_0901.py"
network_class_name: "Split_onset_pitch"
use_strongly_dataset: True
training_dataset_dir: "JBM555_dataset/JBM555_train"
training_gt_pkl_label: "JBM555_train_strong.pkl"
use_weakly_dataset: True
training_weakly_dataset_dir: "JBM555_dataset/JBM555_train"
training_weakly_gt_pkl_label: "JBM555_train_weak.pkl"
val_dataset_dir: "JBM555_dataset/JBM555_validation"
val_gt_pkl_label: "JBM555_valid_strong.pkl"
h5py_feature_file_name: "feature.hdf5"
epoch: 100
warmup_epoch: 5
lr: 0.0001
batch_size: 1
model_save_dir: "models"
model_save_prefix: "jbm555"
log_path: "logger_ctc_ce_jbm555.pkl"